# Neural Network Fundamentals


## Linearly Separable Data Generation

Generate two clusters of points that can be linearly separated in 2D space:

- Use `np.random.randn()` to create two clusters of 100 points each, representing different classes
- Move the mean of each cluster to [-2, -2] and [2, 2] respectively
- Assign classes -1 and 1 to these clusters
- Combine and shuffle the points
- Return points and classes as numpy arrays of shape (N, 2) and (N, 1)

In [1]:
# Import the necessary library
import numpy as np

# Function to generate linearly separable data
def generate_linearly_separable_data():
    # Generate two clusters of 100 points each with standard normal distribution
    cluster1 = np.random.randn(100, 2) + np.array([-2, -2])  # shift mean to [-2, -2]
    cluster2 = np.random.randn(100, 2) + np.array([2, 2])    # shift mean to [2, 2]

    # Assign classes -1 to cluster1 and 1 to cluster2
    labels1 = np.full((100, 1), -1)
    labels2 = np.full((100, 1), 1)

    # Combine the points and labels
    points = np.vstack((cluster1, cluster2))
    labels = np.vstack((labels1, labels2))

    # Shuffle the combined points and labels
    indices = np.random.permutation(len(points))
    points_shuffled = points[indices]
    labels_shuffled = labels[indices]

    return points_shuffled, labels_shuffled

# Generate the data
points, labels = generate_linearly_separable_data()

# Display the shape of the generated arrays
print("Points shape:", points.shape)
print("Labels shape:", labels.shape)

# Display first few points and their labels
print("\nFirst 5 points:\n", points[:5])
print("First 5 labels:\n", labels[:5])


Points shape: (200, 2)
Labels shape: (200, 1)

First 5 points:
 [[-0.69470853 -2.15834668]
 [ 2.9033341   0.40985603]
 [-1.57473902 -1.88315105]
 [ 1.20271442  1.21956446]
 [-2.03151379 -2.85435867]]
First 5 labels:
 [[-1]
 [ 1]
 [-1]
 [ 1]
 [-1]]


## XOR Dataset Generation

Generate the XOR dataset:

- Four points: [[0, 0], [0, 1], [1, 0], [1, 1]]
- Classes: [-1, 1, 1, -1] (XOR logic)
- Return points and classes as numpy arrays

In [2]:
def generate_xor_data():
    # Define the 4 XOR points
    points = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

    # Compute XOR for each point and map [0, 1] to [-1, 1]
    labels = np.array([1 if x != y else -1 for x, y in points]).reshape(-1, 1)

    return points, labels

# Generate the XOR data and display
xor_points, xor_labels = generate_xor_data()
xor_points, xor_labels


(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[-1],
        [ 1],
        [ 1],
        [-1]]))

## Data Visualization

Visualize the clusters and their labels using different colors with matplotlib.